services:
  - type: web
    name: task-planner-agent
    env: python
    pythonVersion: "3.12"  # ← ADD THIS LINE
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    autoDeploy: true